### ISSUE TITLE
Path not found error

### ISSUE THREAD

**Issue by JanZrimec** [bioasp/meneco#34]
When running from notebook or commandline with Meneco v2.0.2 I get the following error:

```
> meneco -d draft.sbml -s seeds.sbml -t targets.sbml -r bigg_universal_v16.sbml
Reading draft network ...
Draft network file: draft.sbml
Reading seeds ...
Seeds file: seeds.sbml
Reading targets ...
Targets file: targets.sbml

Checking draftnet for unproducible targets ...
Traceback (most recent call last):
  File "C:\Users\JanZ\Anaconda3\envs\meneco\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\JanZ\Anaconda3\envs\meneco\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\JanZ\Anaconda3\envs\meneco\Scripts\meneco.exe\__main__.py", line 7, in <module>
  File "C:\Users\JanZ\Anaconda3\envs\meneco\lib\site-packages\meneco\__main__.py", line 12, in main_meneco
    cmd_meneco(sys.argv[1:])
  File "C:\Users\JanZ\Anaconda3\envs\meneco\lib\site-packages\meneco\meneco.py", line 71, in cmd_meneco
    args.json,
  File "C:\Users\JanZ\Anaconda3\envs\meneco\lib\site-packages\meneco\meneco.py", line 137, in run_meneco
    model = query.get_unproducible(draftnet, seeds, targets)
  File "C:\Users\JanZ\Anaconda3\envs\meneco\lib\site-packages\meneco\query.py", line 43, in get_unproducible
    models = clyngor.solve(prg, options=options, use_clingo_module=False)
  File "C:\Users\JanZ\Anaconda3\envs\meneco\lib\site-packages\clyngor\solving.py", line 64, in solve
    files = tuple(map(cleaned_path, files) if clean_path else files)
  File "C:\Users\JanZ\Anaconda3\envs\meneco\lib\site-packages\clyngor\utils.py", line 272, in cleaned_path
    open(path)  # will raise FileExistsError
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\JanZ\\Anaconda3\\envs\\meneco\\lib\\site-packages\\meneco\\query.py\\encodings\\unproducible_targets.lp'
```

Seems like an incorrectly formatted file string with 'query.py' inside? As the path 'C:\\Users\\JanZ\\Anaconda3\\envs\\meneco\\lib\\site-packages\\meneco\\encodings\\unproducible_targets.lp' does exist

 ```
ls C:\\Users\\JanZ\\Anaconda3\\envs\\meneco\\lib\\site-packages\\meneco\\encodings


    Directory: C:\Users\JanZ\Anaconda3\envs\meneco\lib\site-packages\meneco\encodings


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         1/24/2023   6:51 PM           3402 card_min_completions_all_targets.lp
-a----         1/24/2023   6:51 PM           2967 card_min_completions_all_targets_with_bounds.lp
-a----         1/24/2023   6:51 PM           3321 completions_all_targets.lp
-a----         1/24/2023   6:51 PM            102 heuristic.lp
-a----         1/24/2023   6:51 PM           2088 ireactions.lp
-a----         1/24/2023   6:51 PM           1012 unproducible_targets.lp
```

**Comment by sthiele** [comment]
Hi @JanZrimec,
meneco does not support the windows platform.
But nowadays it might not be so difficult to get it working.
I created a branch st/issue_34 that uses proper os paths to point to the ASP encodings. Maybe you can give it a spin and tell me whether it works for you? If so I can upload a new version.
